; ---------------------------------------------------------------------------
; - PC Speaker Driver - Variables (vars.inc)                                -
; - Copyright (C) 1998-2021 Alexandru Groza of Microprogramming TECHNIQUES  -
; - All rights reserved.                                                    -
; ---------------------------------------------------------------------------
; - License: GNU General Public License v3.0                                -
; ---------------------------------------------------------------------------

; commandline parameters
; ---------------------------------------------------------------------------
  GCmdLineParams         DB   ?

; general program variables
; ---------------------------------------------------------------------------
  GIOAddress             DW   ?
  GCommand               DB   ?
